stages:
  - build
  - deploy


image: node:18

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
deploy:
  stage: deploy
  script:
    - npm install -g @azure/static-web-apps-cli
    - swa deploy --app-location ./ --output-location ./dist --env production --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN
  only:
    - main
